### ISSUE TITLE
Exception thrown when attempting to extract missing value

### ISSUE THREAD

**Issue by propensive** [propensive/rapture-json#23]
The following throws a `MissingValueException`:

```
val json = json"""{ "foo": "bar" }"""
json.missing.as[Option[String]]
```

**Comment by propensive** [comment]
Still not working in 1.1.0 with JSON4S, as reported by Jim Newsham:

```
import rapture.json._
import rapture.json.Json
import rapture.json.jsonBackends.json4s._

object TestRaptureJsonOption extends App {
    val json = json"""{ "foo": "bar" }"""
    println(json.missing.as[Option[String]])
  
}

Exception:

Exception in thread "main" rapture.data.MissingValueException: Missing value: <value>.missing
```

**Comment by jedesah** [comment]
I can confirm that it is not working with Jawn as well in 1.1.0.

Let us know if there is anything we can do to help with the rewrite of this part of the extraction system to help things along. I noticed that there are no tests in rapture-json. Is that something you would be interested in adding if someone were to come forward to write some?

**Comment by propensive** [comment]
The problem is independent of the backend, unfortunately.

Thanks for the offer of help! The tests are actually all in a separate project - `rapture-json-test`, though it's currently nontrivial to bootstrap the test rig (it requires a few as-yet unreleased projects to be built), so I haven't made it too obvious yet. I'm working on improving this, slowly, but it's realistically a lower priority than things like fixing this issue... ;)

**Comment by nightscape** [comment]
I assume the best work-around atm is pattern matching like this?
```scala
val js = json"""{ "foo": "bar" }"""
json match {
  case json"""{"missing" : $value}""" => Some(value.as[String])
  case _ => None
}

**Comment by propensive** [comment]
@nightscape Oh, I hadn't thought of using pattern matching as a workaround, but that ought to work. I just experimented with a less repetitive version of this workaround, specifically a redefinition of the `Option[T]` extractor, but it doesn't help as (IIRC) the buggy code has already been run by the time it reaches the extractor.

Just to repeat myself, this issue *has* been fixed in master, though I've got a couple more issues to look at before I can make the next release, so that's what's holding this up for now.

**Comment by propensive** [comment]
@nightscape Oh, I hadn't thought of using pattern matching as a workaround, but that ought to work. I just experimented with a less repetitive version of this workaround, specifically a redefinition of the `Option[T]` extractor, but it doesn't help as (IIRC) the buggy code has already been run by the time it reaches the extractor.

Just to repeat myself, this issue *has* been fixed in master, though I've got a couple more issues to look at before I can make the next release, so that's what's holding this up for now.

**Comment by sam** [comment]
Just wondering if there were any updates on this one?
